paths:
  temp_dir: ./tmp
  output_dir: ./output
ffmpeg:
  prefer_center: true
  filter_chain: "highpass=f=60,lowpass=f=10000,aformat=sample_fmts=flt,aresample=resampler=soxr:osf=flt:osr=16000"
separation:
  backend: fv4
  sep_hz: 44100
  prefer_center: true
  prefer_gpu: true
  fv4:
    cfg: ./models/voc_gabox.yaml
    ckpt: ./models/voc_fv4.ckpt
parakeet:
  force_float32: true
  prefer_gpu: true
